### ISSUE TITLE
.jar is missing from repo?

### ISSUE THREAD

**Issue by imekachi** [JordanForeman/idea-snazzy#3]
I really love the snazzy theme and I appreciated you port it to IDEA (I'm finding a way to port this theme to my Webstorm IDE and I finally found this repo).

From README.md you said that 

> Download either the .jar or .ics file ...

but i cannot find .jar file on this repo
and I tried importing the .icls file , it doesn't work

> The 'snazzy.icls' contains no settings to import.
Please make sure you have generated the file using 'File|Export Settings' feature.

OS: Windows 8.1
IDE: WebStorm 2018.2 Build #WS-182.3684.70, built on July 20, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by imekachi** [comment]
Oh I was trying to import it by
`File -> Import Settings`

I just tried `Settings -> Color Scheme -> import` and it works now
Thanks

**Comment by JordanForeman** [comment]
@imekachi thanks for calling this out! When I first created this repo I was committing both the `jar` and the `icls` file. Because I wanted to open-source this and I didn't want to open the door to folks trying to merge potentially malicious `jar`s I opted to stop doing that. I never updated the readme though!

I've removed references to the `jar` file in the `readme`.

Also, 

> import into IntelliJ (or other JetBrains IDEs) using the built-in color scheme manager.

I suppose this could potentially be made clearer?
